### ISSUE TITLE
specify geographical location of table in pandas read_gbq

### ISSUE THREAD

**Issue by rmporsch** [pydata/pandas-gbq#177]
I am having trouble setting the geographical location in `pandas.read_gbq`.

In `google.cloud.bigquery` I can set the location to `asia-northeast1` the following:

```
from google.cloud import bigquery
bigquery_client = bigquery.Client(project_name)    
query_job = bigquery_client.query(query, location='asia-northeast1')

```
However, I fail to do this in `read_gbq`. The following seems not to  work:

```
from pandas_gbq import gbq    
dat = gbq.read_gbq(query, project_id=project_name, jobReference={'location':'asia-northeast1'}, dialect='standard')
```

**Comment by maxim-lian** [comment]
Thanks for the report!

I'm not familiar with this - what's the error you get when setting this? And when it's not set?

**Comment by tswast** [comment]
@rmporsch You're correct that this requires modifications to `pandas-gbq`.

Note: the way I would expect this to work is by using the `configuration` argument to `read_gbq`.

```
import pandas_gbq
pandas_gbq.read_gbq(
    "SELECT name FROM tokyo_dataset.us_states WHERE post_abbr LIKE 'W%'",
    configuration={'jobReference':{'location':'asia-northeast1'}},
    project_id='swast-scratch')
```

but this fails (I believe because the `jobReference` key gets overwritten by `google-cloud-bigquery` when no `job_id` is passed in.

**Comment by tswast** [comment]
I think the proper fix here is to add a `location` parameter to `read_gbq` and `to_gbq` so that we can pass it on to the `google-cloud-bigquery` library when we [run the query](https://github.com/pydata/pandas-gbq/blob/08166685d3305a57fbfd3bc4c41a1cf5df98ebcf/pandas_gbq/gbq.py#L244) or [load job](https://github.com/pydata/pandas-gbq/blob/08166685d3305a57fbfd3bc4c41a1cf5df98ebcf/pandas_gbq/load.py#L71).

Aside: I'd like to make this less verbose once there is a way to set a default location in the BigQuery client object. https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5148

**Comment by tswast** [comment]
Once #185 is in, we'll need to

- [ ] Release pandas-gbq 0.5.0.
- [ ] Update pandas to add the location parameter to `DataFrame.to_gbq` and `pandas.read_gbq`.

**Comment by tswast** [comment]
Version 0.5.0 is now released to PyPI with this fix. Next steps are to add the location parameters to Pandas.
