### ISSUE TITLE
support new version of datalab

### ISSUE THREAD

**Issue by yoavMoon** [pydata/pandas-gbq#199]
I'm getting this incompatibility error when upgrading pandas-gbq:

**google-cloud-monitoring 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.3.0 which is incompatible.**

 My datalab version is: 1.2.20180818

**Comment by max-sixty** [comment]
Thanks for posting an issue @yoavMoon 

That looks like the dependency runs datalab -> monitoring -> api-core. pandas-gbq requires a new-ish version of api-core. 

For your case - try it and see if it works. datalab pins its dependencies more than is required, in my experience, and you may not need the monitoring library at all
For the broader case - I think the issue is on datalab to support reasonably recent versions of google libraries

**Comment by tswast** [comment]
@yoavMoon You could try upgrading `google-cloud-monitoring` on datalab before upgrading `pandas-gbq`.

But, yes @max-sixty is right. Ultimately it is on the Datalab team to keep up with latest versions of libraries.

**Comment by max-sixty** [comment]
@yoavMoon please reopen if you still have issues with this, cheers
