### ISSUE TITLE
`to_gbq` incorrectly converts unsigned integers to strings

### ISSUE THREAD

**Issue by jamesthimont** [pydata/pandas-gbq#220]
in `schema.py` the field mapping is missing the _u_ datatype

```
type_mapping = {
        "i": "INTEGER",
        "b": "BOOLEAN",
        "f": "FLOAT",
        "O": "STRING",
        "S": "STRING",
        "U": "STRING",
        "M": "TIMESTAMP",
    }
```

**Comment by max-sixty** [comment]
Thanks for the issue @jamesthimont 

Does pandas handle unsigned integers? I haven't come across that

**Comment by jamesthimont** [comment]
@max-sixty pandas does handle them

**Comment by max-sixty** [comment]
Thanks @jamesthimont . Please could you post an example? I'd like to understand how they're encoded to assess whether we could keep them as ints

**Comment by tswast** [comment]
To avoid overflow issues, the destination for unsigned integers should be the [BigQuery NUMERIC type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric-type), as [integers are always signed in BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#integer-type), but that still might mean some problems for a round-trip between pandas and BigQuery because the Python client library converts NUMERIC columns to decimal.

**Comment by max-sixty** [comment]
Closing as stale, please reopen if there's a repro example
