### ISSUE TITLE
Big Query Storage API 400ing

### ISSUE THREAD

**Issue by megancooper** [pydata/pandas-gbq#305]
I am attempting to query BigQuery storage api from a spark script running on AWS EMR. For some all requests to BigQuery storage api are 400ing and are (redirecting?) to the BigQuery API. (See images below). Why is this happening?

All of my queries are `select count(*) from dataset.table ... ` queries that are quick and have minimal filters.
```
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/home/hadoop/credentials.json'
pandas_gbq.context.use_bqstorage_api = True
df = pandas_gbq.read_gbq(query, 
        project_id="<project>", 
        use_bqstorage_api=True)
count=  df['f0_'][0]
```

**BigQuery Storage API**

![Screen Shot 2019-12-13 at 11 02 19 PM](https://user-images.githubusercontent.com/8683055/70843720-f786eb80-1dfc-11ea-9d98-ce930aea28fd.png)

**BigQuery API**

![Screen Shot 2019-12-13 at 11 06 14 PM](https://user-images.githubusercontent.com/8683055/70843741-3026c500-1dfd-11ea-878c-a9d495d0f6bc.png)

**Comment by tswast** [comment]
400s are expected for queries with small results (at least for now). The BigQuery Storage API is unable to read from small (less than about 100MB) [temporary anonymous tables](https://cloud.google.com/bigquery/docs/writing-results#temporary_and_permanent_tables).

This limitation is documented at https://cloud.google.com/bigquery/docs/reference/storage/#limitations

> In some cases, reading small anonymous (cached) tables is disallowed via the BigQuery Storage API.

Since this is a backend issue, I recommend filing a request at https://issuetracker.google.com/issues/new?component=187149&template=1162659 and/or support ticket to make sure the BigQuery backend team prioritizes fixing this limitation.
